name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  gap: ^3.0.1
  go_router: ^16.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.7.0
  core:
    path: packages/core
  domain:
    path: packages/domain
  data:
    path: packages/data
  get_it: ^8.1.0
  logger: ^2.6.1
  mocktail: ^1.0.4
  freezed_annotation: ^3.1.0
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.1
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  intl: ^0.20.2
  lottie: ^3.3.1
  cached_network_image: ^3.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  retrofit_generator: ^10.0.1
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/svg/
    - assets/lottie/