
name: response_wrapper
description: A Response Wrapper for the API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  freezed_annotation: ^3.1.0
  http: ^1.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.6.0
  display_api:
    path: ../display_api

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1
  mocktail: ^1.0.0
  test: ^1.16.4