name: core
description: Dart package which manages the core of the application
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.0.0
  dio: 
  logger: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  


