name: core
description: Dart package which manages the core of the application
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  


