name: domain
description: Dart package which manages the domain layer.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  retrofit: ^4.6.0
  logger: ^2.6.0  # for logging purpose
  dio: ^5.8.0+1
  core:
    path: ../core
  get_it: ^8.2.0
  injectable: ^2.5.1
  injectable_generator: ^2.8.1
  kakao_flutter_sdk_user: ^1.9.7+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1


